import Head from "next/head";
import Image from "next/image";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className=" w-screen h-auto bg-white p-3">
                <Image
                    src="/../public/img/logo.png"
                    alt="Logo"
                    height={46}
                    width={102}
                />
            </div>
        </div>
    );
}
